github_changelog_generator:
  # Exclude issues or PRs with these labels
  exclude_labels: duplicate,invalid,wontfix
  # Specify categories for organizing the changelog
  categories:
    - title: 🚀 Features
      labels: feature,enhancement
    - title: 🐛 Bug Fixes
      labels: bug
    - title: 🛠 Maintenance
      labels: chore,refactor
  # Ignore certain milestones or projects
  ignore:
    milestones: 'none'
    projects: 'none'
  # Other customization options as needed
