user: DanielButler
project: VS_Code_Catalog_Json_Editor
token: $GITHUB_TOKEN
output: CHANGELOG.md
exclude_labels: duplicate,invalid,wontfix
no_issue: true
categories:
  - title: 🚀 Features
    labels: feature, enhancement, improvement
  - title: 🐛 Bug Fixes
    labels: bug
  - title: 🛠 Maintenance
    labels: chore, refactor
  - title: 📝 Documentation
    labels: docs
  - title: ⚡ Performance
    labels: performance
  - title: ✅ Tests
    labels: test
  - title: 🆘 Hotfixes
    labels: hotfix
