name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [20.x]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: npm ci

    - name: Run tests on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install -y xvfb
        xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" npm test

    - name: Run tests on Windows
      if: matrix.os == 'windows-latest'
      run: npm test

    - name: Run tests on macOS
      if: matrix.os == 'macos-latest'
      run: npm test

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.os }}-${{ github.run_id }}
        path: test-results
