name: CI

on:
  pull_request:
    branches: [ main ]

permissions:
  checks: write
  contents: write

jobs:
  test:
    strategy:
      fail-fast: false  # Allows all matrix jobs to run to completion
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [20.x]
    runs-on: ${{ matrix.os }}
    env:
      CI: true
      FORCE_COLOR: 1
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Create Test Results Directory
        shell: bash
        run: mkdir -p test-results

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        id: run-tests
        continue-on-error: true  # Allow the workflow to continue even if tests fail
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y xvfb
            xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" npm test
          else
            npm test
          fi

      - name: Check for Test Report
        id: check-report
        if: always()  # Run even if tests fail
        shell: bash
        run: |
          if [ -f "test-results/test-report.xml" ]; then
            echo "Test report exists"
            cat test-results/test-report.xml
          else
            echo "Test report missing"
            mkdir -p test-results
            echo '<?xml version="1.0"?><testsuites><testsuite name="Failed to generate report" errors="1" failures="1" tests="1"><testcase name="Test Execution"><failure message="Failed to generate test report">Test execution failed and no report was generated</failure></testcase></testsuite></testsuites>' > test-results/test-report.xml
          fi

      - name: Upload Test Results
        if: always()  # Ensures this step runs even if previous steps fail
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}-${{ github.run_id }}
          path: test-results
          retention-days: 7

      - name: Report Test Results
        if: always()  # Ensures this step runs even if previous steps fail
        uses: dorny/test-reporter@v1
        with:
          name: Test Results - ${{ matrix.os }} - ${{ matrix.node-version }}
          path: test-results/*.xml
          reporter: java-junit
          path-replace-backslashes: false
          list-suites: all
          list-tests: all
          max-annotations: 50
          fail-on-error: false

      # Fail the workflow if tests failed
      - name: Check Test Results
        if: steps.run-tests.outcome != 'success'
        run: exit 1
