# .github/workflows/ci.yml

name: CI

on:
  pull_request:
    branches: [ main ]

permissions:
  checks: write
  contents: write

jobs:
  test:
    strategy:
      fail-fast: false  # Allows all matrix jobs to run to completion
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [20.x]
    runs-on: ${{ matrix.os }}
    env:
      CI: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        shell: bash
        run: |
          if [ "$RUNNER_OS" == 'Linux' ]; then
            sudo apt-get update
            sudo apt-get install -y xvfb
            xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" npm test
          else
            npm test
          fi

      - name: Upload Test Results
        if: always()  # Ensures this step runs even if previous steps fail
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}-${{ github.run_id }}
          path: test-results

      - name: Report Test Results
        if: always()  # Ensures this step runs even if previous steps fail
        uses: dorny/test-reporter@v1
        with:
          name: Test Results - ${{ matrix.os }} - ${{ matrix.node-version }}
          path: test-results/*.xml
          reporter: java-junit
          path-replace-backslashes: false
          list-suites: all
          list-tests: all
          max-annotations: 10
          fail-on-error: true
          fail-on-empty: true
